services:
  rabbitmq:
    image: rabbitmq:3.13-management
    container_name: rabbitmq-assign
    ports:
      - "5672:5672"   # AMQP port for apps
      - "15672:15672" # Web UI (Management)
    environment:
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: pass
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "ping"]
      interval: 5s
      timeout: 5s
      retries: 10
